name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Instala Dart o Flutter
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      # Instala dependencias
      - run: flutter pub get

      # Compila tu app web (si usas Flutter cambia el comando)
      - run: flutter compile js -o build/web/main.dart.js web/main.dart

      # Publica a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
