name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Instala Dart o Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      # Instala dependencias
      - run: flutter pub get

      - run: flutter build web

      # Publica a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
